# Site Settings
title:               MiFancl
tagline:             a tiny little blog
description:
baseurl:            #"/"
url:                #"https://mifancl.github.io"
github:
  url:               #"https://mifancl.github.io/"
author:
  name:              "Xiong Hu"
  email:             "mifancl@gmail.com"
  twitter:           "paululele"
  instagram:         "paululele"
  github:            "mifancl"
  facebook:          "Le.Paul.94"
  linkedin:          "lenpaul"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
